storage: /tmp/verdaccio-storage

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@rnef/*':
    access: $all
    publish: $all
  '**':
    access: $all
    proxy: npmjs

# This options does not seem to react to changes when used with `runServer()` node API
# Maybe upgrade to Verdaccio 6.x will help
# See: https://github.com/verdaccio/verdaccio/issues/3728
logs:
  - { type: stdout, format: pretty, level: info }
