name: 'RNEF Remote Build - iOS Simulator'
description: 'Github implementation of the RNEF Remote Build for iOS Simulator'

inputs:
  github-token:
    description: 'GitHub Token'
    required: false
    default: ${{ github.token }}
  scheme:
    description: Xcode scheme to build
    required: false
    default: 'HelloWorld'
  mode:
    description: Xcode scheme build configuration
    required: false
    default: 'Debug'

outputs:
  artifact-url:
    description: 'URL of the relevant iOS Simulator build artifact (could be cached)'
    value: ${{ steps.cached-url.outcome == 'success' && steps.cached-url.outputs.artifact-url || steps.upload-artifact.outputs.artifact-url }}

runs:
  using: 'composite'
  steps:
    - name: Native Fingerprint
      id: fingerprint
      uses: ./.github/actions/rnef-native-fingerprint
      with:
        platform: ios

    - name: Set artifact name
      run: |
        echo "ARTIFACT_NAME=rnef-ios-${{ inputs.mode }}-${{ steps.fingerprint.outputs.hash}}" >> $GITHUB_ENV
      shell: bash

    - name: Find artifact URL
      id: cached-url
      uses: ./.github/actions/find-artifact
      with:
        name: ${{ env.ARTIFACT_NAME }}

    - name: Post Cached Build (if found)
      if: ${{ steps.cached-url.outputs.artifact-url && github.event_name == 'pull_request' }}
      uses: ./.github/actions/rnef-post-build
      with:
        platform: iOS Simulator
        artifact-url: ${{ steps.cached-url.outputs.artifact-url }}

    - name: Install Pods
      if: ${{ !steps.cached-url.outputs.artifact-url }}
      run: |
        cd ios
        pod install
      shell: bash

    - name: Build iOS
      if: ${{ !steps.cached-url.outputs.artifact-url }}
      run: |
        cd ios
        npx rnef build:ios --buildFolder="build" --verbose
      shell: bash

    - name: Find Build Artifact
      if: ${{ !steps.cached-url.outputs.artifact-url }}
      run: |
        # Need to compress with tar, as GH actions drop execute file permission during packing to zip
        APP_PATH=$(find ios/build/Build/Products/Debug-iphonesimulator -maxdepth 1 -name '*.app' -type d | head -1)
        APP_DIR=$(dirname "$APP_PATH")
        APP_BASENAME=$(basename "$APP_PATH")

        ARTIFACT_PATH="$APP_DIR/app.tar.gz"
        tar -C "$APP_DIR" -czvf "$ARTIFACT_PATH" "$APP_BASENAME"

        echo "ARTIFACT_PATH=$ARTIFACT_PATH" >> $GITHUB_ENV
      shell: bash

    - name: Upload Artifact
      id: upload-artifact
      if: ${{ !steps.cached-url.outputs.artifact-url }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.ARTIFACT_PATH }}
        if-no-files-found: error

    - name: Post Build
      if: ${{ !steps.cached-url.outputs.artifact-url && github.event_name == 'pull_request' }}
      uses: ./.github/actions/rnef-post-build
      with:
        platform: iOS Simulator
        artifact-url: ${{ steps.upload-artifact.outputs.artifact-url }}
