name: Remote Build Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency: 
  group: remote-build-android-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node  
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: RNEF Remote Build - Android
        id: rnef-remote-build-android
        uses: ./.github/actions/rnef-remote-build-android
