# Note: this action will be published separate on the GitHub.
# It's here only temporary for the development purposes.

name: 'RNEF Remote Build - Android'
description: 'Github implementation of the RNEF Remote Build for Android'

inputs:
  github-token:
    description: 'GitHub Token'
    required: false
    default: ${{ github.token }}
  artifact-output-path:
    description: 'Path to the build output artifact'
    required: false
    default: 'android/app/build/outputs/apk/debug/app-debug.apk'
  mode:
    description: 'Build mode'
    required: false
    default: 'debug'
  tasks:
    description: 'Gradle tasks to run'
    required: false
    default: 'assembleDebug'
  rnef-build-extra-params:
    description: 'Extra parameters to pass to "rnef build:android"'
    required: false

outputs:
  artifact-url:
    description: 'URL of the relevant Android build artifact (could be cached)'
    value: ${{ steps.cached-url.outcome == 'success' && steps.cached-url.outputs.artifact-url || steps.upload-artifact.outputs.artifact-url }}

runs:
  using: 'composite'
  steps:
    - name: Native Fingerprint
      id: fingerprint
      uses: ./.github/actions/rnef-native-fingerprint
      with:
        platform: android

    - name: Set artifact name
      run: |
        echo "ARTIFACT_NAME=rnef-android-${{ inputs.mode }}-${{ steps.fingerprint.outputs.hash}}" >> $GITHUB_ENV
      shell: bash

    - name: Find artifact URL
      id: cached-url
      uses: ./.github/actions/find-artifact
      with:
        name: ${{ env.ARTIFACT_NAME }}

    - name: Post Cached Build (if found)
      if: ${{ steps.cached-url.outputs.artifact-url && github.event_name == 'pull_request' }}
      uses: ./.github/actions/rnef-post-build
      with:
        platform: Android
        artifact-url: ${{ steps.cached-url.outputs.artifact-url }}

    - name: Install Java
      if: ${{ !steps.cached-url.outputs.artifact-url }}
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: adopt
        cache: gradle

    - name: Validate Gradle wrapper
      if: ${{ !steps.cached-url.outputs.artifact-url }}
      uses: gradle/actions/wrapper-validation@v4

    - name: Build Android
      if: ${{ !steps.cached-url.outputs.artifact-url }}
      run: |
        npx rnef build:android \
          --mode "${{ inputs.mode }}" \
          --tasks "${{ inputs.tasks }}" \
          ${{ inputs.rnef-build-extra-params }}
      shell: bash

    - name: Upload Artifact
      id: upload-artifact
      if: ${{ !steps.cached-url.outputs.artifact-url }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ inputs.artifact-output-path }}
        if-no-files-found: error

    - name: Post Build
      if: ${{ !steps.cached-url.outputs.artifact-url && github.event_name == 'pull_request' }}
      uses: ./.github/actions/rnef-post-build
      with:
        platform: Android
        artifact-url: ${{ steps.upload-artifact.outputs.artifact-url }}
