# Note: this action will be published separate on the GitHub.
# It's here only temporary for the development purposes.

name: 'RNEF Remote Build - Android'
description: 'Github implementation of the RNEF Remote Build for Android'

inputs:
  github-token:
    description: "GitHub Token"
    required: false
    default: ${{ github.token }}
  artifact-output-path:
    description: "Path to the build output artifact"
    required: false
    default: "android/app/build/outputs/apk/debug/app-debug.apk"
  artifact-name-prefix:
    description: "Prefix for the artifact name"
    required: false
    default: "app-debug"
  artifact-name-extension:
    description: "File extension for the artifact name"
    required: false
    default: "apk"

outputs:
  artifact-url:
    description: 'URL of the relevant Android build artifact (could be cached)'
    value: ${{ steps.cached-url.outcome == 'success' && steps.cached-url.outputs.artifact-url || steps.upload-artifact.outputs.artifact-url }}

runs:
  using: "composite"
  steps:
    - name: Native Fingerprint
      id: fingerprint
      uses: ./.github/actions/rnef-native-fingerprint
      with:
        platforms: android

    - name: Find artifact URL
      id: cached-url
      uses: ./.github/actions/find-artifact
      with:
        name: ${{inputs.artifact-name-prefix}}-${{ steps.fingerprint.outputs.hash}}.${{inputs.artifact-name-extension}}

    - name: Post Cached Build (if found)
      if: steps.cached-url.outputs.artifact-url
      uses: ./.github/actions/rnef-post-build
      with:
        platform: Android
        artifact-url: ${{ steps.cached-url.outputs.artifact-url }}
    
    - name: Install Java
      if: ${{ !steps.cached-url.outputs.artifact-url }}
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: adopt
        cache: gradle
  
    - name: Validate Gradle wrapper
      if: ${{ !steps.cached-url.outputs.artifact-url }}
      uses: gradle/actions/wrapper-validation@v4

    - name: Build Android
      if: ${{ !steps.cached-url.outputs.artifact-url }}
      run: |
        cd android
        pnpm rnef build:android --tasks assembleDebug
      shell: bash

    - name: Upload APK
      id: upload-artifact
      if: ${{ !steps.cached-url.outputs.artifact-url }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{inputs.artifact-name-prefix}}-${{ steps.fingerprint.outputs.hash}}.${{inputs.artifact-name-extension}}
        path: ${{ inputs.artifact-output-path }}
        if-no-files-found: error

    - name: Post Build
      if: ${{ !steps.cached-url.outputs.artifact-url }}
      uses: ./.github/actions/rnef-post-build
      with:
        platform: Android
        artifact-url: ${{ steps.upload-artifact.outputs.artifact-url }}
