name: 'RNEF Remote Build - iOS'
description: 'Github implementation of the RNEF Remote Build for iOS'

inputs:
  github-token:
    description: GitHub Token
    required: false
    default: ${{ github.token }}
  destination:
    description: 'Destination to build to: "simulator" or "device". Using "device" runs "rnef build:ios --archive" and code signing settings (certificate, provisioning profile, keychain password) are required.'
    required: false
    default: 'simulator' # 'simulator' or 'device'
  configuration:
    description: Xcode scheme configuration
    required: false
    default: 'Debug'
  certificate-base64:
    description: '[Device Builds] Base64 encoded P12 file containing Apple certificate (incl. private key)'
    required: false
  certificate-password:
    description: '[Device Builds] Password for the P12 file containing the Apple certificate'
    required: false
  provisioning-profile-base64:
    description: '[Device Builds] Base64 encoded Apple provisioning profile (*.mobileprovision)'
    required: false
  provisioning-profile-name:
    description: '[Device Builds] Name of the Apple provisioning profile (without .mobileprovision extension)'
    required: false
  keychain-password:
    description: '[Device Builds] Password that will protect temporary keychain used for signing (can be a random string)'
    required: false
  rnef-build-extra-params:
    description: 'Extra parameters to pass to "rnef build:ios"'
    required: false
  comment-bot:
    description: 'Whether to send a comment under PR with the link to the generated build'
    required: false
    default: true

outputs:
  artifact-url:
    description: 'URL of the relevant iOS build artifact (could be cached)'
    value: ${{ steps.cached-url.outcome == 'success' && steps.cached-url.outputs.artifact-url || steps.upload-artifact.outputs.artifact-url }}

runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      run: |
        if [ "${{ inputs.destination }}" != "simulator" ] && [ "${{ inputs.destination }}" != "device" ]; then
          echo "Invalid input 'destination': '${{ inputs.destination }}'. Allowed values: 'simulator' or 'device'."
          exit 1
        fi

        if [ "${{ inputs.destination }}" == "device" ]; then
          if [ -z "${{ inputs.certificate-base64 }}" ]; then
            echo "Input 'certificate-base64' is required for device builds."
            exit 1
          fi

          if [ -z "${{ inputs.certificate-password }}" ]; then
            echo "  Input 'certificate-password' is required for device builds."
            exit 1
          fi

          if [ -z "${{ inputs.provisioning-profile-base64 }}" ]; then
            echo "Input 'provisioning-profile-base64' is required for device builds."
            exit 1
          fi

          if [ -z "${{ inputs.provisioning-profile-name }}" ]; then
            echo "Input 'provisioning-profile-name' is required for device builds."
            exit 1
          fi

          if [ -z "${{ inputs.keychain-password }}" ]; then
            echo "Input 'keychain-password' is required for device builds."
            exit 1
          fi
        fi
      shell: bash

    - name: Native Fingerprint
      id: fingerprint
      uses: ./.github/actions/rnef-native-fingerprint
      with:
        platform: ios

    - name: Set environment variables
      run: |
        echo "ARTIFACT_NAME=rnef-ios-${{ inputs.destination }}-${{ inputs.configuration }}-${{ steps.fingerprint.outputs.hash}}" >> $GITHUB_ENV
        echo "PROFILE_DIR=$HOME/Library/MobileDevice/Provisioning Profiles" >> $GITHUB_ENV
      shell: bash

    - name: Find artifact URL
      id: cached-url
      uses: ./.github/actions/find-artifact
      with:
        name: ${{ env.ARTIFACT_NAME }}

    - name: Post Cached Build (if found)
      if: ${{ steps.cached-url.outputs.artifact-url && github.event_name == 'pull_request' }}
      uses: ./.github/actions/rnef-post-build
      with:
        title: iOS ${{ inputs.configuration }} ${{ inputs.destination == 'simulator' && 'APP for simulators' || 'IPA for physical devices' }}
        artifact-url: ${{ steps.cached-url.outputs.artifact-url }}

    - name: Setup Code Signing (device builds only)
      if: ${{ !steps.cached-url.outputs.artifact-url && inputs.destination == 'device' }}
      run: |
        # Create temporary keychain
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

        security create-keychain -p "${{ inputs.keychain-password }}" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "${{ inputs.keychain-password }}" $KEYCHAIN_PATH

        # Import certificate to keychain                
        CERTIFICATE_PATH=$RUNNER_TEMP/certificate.p12

        echo -n "${{ inputs.certificate-base64 }}" | base64 --decode -o $CERTIFICATE_PATH
        security import $CERTIFICATE_PATH -P "${{ inputs.certificate-password }}" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security set-key-partition-list -S apple-tool:,apple: -k "${{ inputs.keychain-password }}" $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH

        # Unpack provisioning profile
        PROFILE_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"
        PROFILE_PATH="$PROFILE_DIR/${{ inputs.provisioning-profile-name }}.mobileprovision"

        mkdir -p "$PROFILE_DIR"
        echo -n "${{ inputs.provisioning-profile-base64 }}" | base64 --decode -o "$PROFILE_PATH"
      shell: bash

    - name: Determine iOS sourceDir
      if: ${{ !steps.cached-url.outputs.artifact-url }}
      run: |
        JSON_OUTPUT=$(npx rnef config -p ios)
        IOS_SOURCE_DIR=$(echo "$JSON_OUTPUT" | jq -r '.project.ios.sourceDir')
        echo "IOS_SOURCE_DIR=$IOS_SOURCE_DIR" >> $GITHUB_ENV
      shell: bash

    - name: Build iOS
      if: ${{ !steps.cached-url.outputs.artifact-url }}
      run: |
        npx rnef build:ios \
          ${{ inputs.destination == 'device' && '--archive' || '' }} \
          --configuration ${{ inputs.configuration }} \
          --build-folder "build" \
          --destination ${{ inputs.destination }} \
          ${{ inputs.rnef-build-extra-params }}
      shell: bash

    - name: Find Build Artifact
      if: ${{ !steps.cached-url.outputs.artifact-url }}
      run: |
        if [ "${{ inputs.destination }}" == "device" ]; then
          IPA_PATH=$(find .rnef/cache/ios/export -maxdepth 1 -name '*.ipa' -type f | head -1)
          echo IPA_PATH $IPA_PATH
          echo "ARTIFACT_PATH=$IPA_PATH" >> $GITHUB_ENV
        else 
          # Simulator build: needs to compress with tar, as GH actions drop execute file permission during packing to zip
          APP_PATH=$(find $IOS_SOURCE_DIR/build -name '*.app' -type d | head -1 )
          APP_DIR=$(dirname "$APP_PATH")
          APP_BASENAME=$(basename "$APP_PATH")

          ARTIFACT_PATH="$APP_DIR/app.tar.gz"
          tar -C "$APP_DIR" -czvf "$ARTIFACT_PATH" "$APP_BASENAME"

          echo "ARTIFACT_PATH=$ARTIFACT_PATH" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Upload Artifact
      id: upload-artifact
      if: ${{ !steps.cached-url.outputs.artifact-url }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.ARTIFACT_PATH }}
        if-no-files-found: error

    - name: Clean Up Code Signing (device builds only)
      if: ${{ !steps.cached-url.outputs.artifact-url && inputs.destination == 'device' }}
      run: |
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
        security delete-keychain "$KEYCHAIN_PATH"

        PROFILE_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"
        PROFILE_PATH="$PROFILE_DIR/${{ inputs.provisioning-profile-name }}.mobileprovision"
        rm "$PROFILE_PATH"
      shell: bash

    - name: Post Build
      if: ${{ !steps.cached-url.outputs.artifact-url && github.event_name == 'pull_request' && inputs.comment-bot == 'true' }}
      uses: ./.github/actions/rnef-post-build
      with:
        title: iOS ${{ inputs.configuration }} ${{ inputs.destination == 'simulator' && 'APP for simulators' || 'IPA for physical devices' }}
        artifact-url: ${{ steps.upload-artifact.outputs.artifact-url }}
