name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup-node

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Run tests
        run: pnpm test

      - name: Run end-to-end tests
        run: |
          # Run in background
          pnpm verdaccio:init &

          npx wait-on@8.0.1 http://localhost:4873
          pnpm verdaccio:publish

          NPM_CONFIG_REGISTRY=http://localhost:4873 pnpm e2e

  check-changeset:
    name: Check Changeset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup-node

      - name: Check changeset
        if: github.ref != 'refs/heads/main'
        run: pnpm changeset status --since=origin/${{ github.base_ref }}

  check-licenses:
    name: Check Licenses
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup-node

      - name: Check licenses
        run: |
          original_dir=$(pwd)
          for dir in ./packages/*; do
            if [ -d "$dir" ]; then
              cd "$dir"
              npx license-kit copyleft
              cd "$original_dir"
            fi
          done
        shell: bash
