name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9.11.0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      - name: Typecheck and lint
        run: pnpm exec nx affected -t typecheck lint

      - name: Run tests
        run: pnpm exec nx affected -t test

      - name: Build
        run: pnpm build

      - name: Run end-to-end tests
        run: |
          pnpm config set registry http://localhost:4873
          node scripts/verdaccio-init.mjs &

          # This is necessary as we have to wait for verdaccio init to finish in the background
          # We can either put sleep here or put some blocking script that would ping local verdaccio instance if it's ready
          sleep 3
          NPM_CONFIG_REGISTRY=http://localhost:4873 pnpm exec nx affected -t e2e

