name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 10.2.1+sha256.f988f0d93b87e1da2d8cdf6ac7f45a01c6f843ae3606b4ca0f2ffd713b85f975

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      - name: Typecheck and lint
        run: pnpm exec nx affected -t typecheck lint

      - name: Run tests
        run: pnpm exec nx affected -t test

      - name: Build
        run: pnpm build

      - name: Run end-to-end tests
        run: |
          # Run in background
          pnpm verdaccio:init &

          npx wait-on@8.0.1 http://localhost:4873
          pnpm verdaccio:publish

          NPM_CONFIG_REGISTRY=http://localhost:4873 pnpm exec nx affected -t e2e
